[project]
name = "marci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "chromadb>=0.6.3",
    "langchain-huggingface>=0.1.2",
    "langchain-text-splitters>=0.3.6",
    "toml>=0.10.2",
    "uvicorn>=0.34.0",
]
